default_language_version:
  python: python3

exclude: |
  (?x)(
    ^venv/|
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        description: Simply check whether files parse as valid python.
      - id: check-builtin-literals
        description: Require literal syntax when initializing empty, or zero Python builtin types.
      - id: check-docstring-first
        description: Checks for a common error of placing code before the docstring.
      - id: check-added-large-files
        description: Prevent giant files from being committed.
        args: ['--maxkb=1024']
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings.
      - id: check-symlinks
        description: Checks for symlinks which do not point to anything.
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax.
        exclude_types: ['binary']
      - id: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: detect-private-key
        description: Checks for the existence of private keys.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      #    - id: mixed-line-ending
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: requirements-txt-fixer
        description: Sorts entries in requirements.txt

  # format python code using black, and check PEP8 with flake8
  - repo: https://github.com/psf/black
    rev: '24.4.0'
    hooks:
      - id: black
        description: The uncompromising Python code formatter
        language_version: python3.8
        #args: ['--force-exclude'] after PR merge: https://github.com/psf/black/pull/1032

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
      - id: mypy
        args: [--config-file,  mypy.ini]
        exclude: '(?x)(cron_scripts/migrations)'

  - repo: local
    hooks:
      - id: tests
        name: tests
        description: Run pytest
        language: system
        entry: pytest -sv
        stages: [push]
